In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction import DictVectorizer
from sklearn.impute import SimpleImputer

In [ ]:
df = pd.read_csv('anime.csv')
df.head()

anime_id                              name  ... rating members
0     32281                    Kimi no Na wa.  ...   9.37  200630
1      5114  Fullmetal Alchemist: Brotherhood  ...   9.26  793665
2     28977                          Gintama°  ...   9.25  114262
3      9253                       Steins;Gate  ...   9.17  673572
4      9969                     Gintama&#039;  ...   9.16  151266

[5 rows x 7 columns]

In [ ]:
imp_mean = SimpleImputer(missing_values=np.nan,strategy='mean')
imp_freq = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imp_median = SimpleImputer(missing_values=np.nan,strategy='median')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   anime_id  12294 non-null  int64  
 1   name      12294 non-null  object 
 2   genre     12232 non-null  object 
 3   type      12269 non-null  object 
 4   episodes  12294 non-null  object 
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64  
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB


In [ ]:
arr_rating = df['rating'].to_numpy()
arr_rating

array([ nan,  nan,  nan, ..., 4.88, 4.98,  nan])

In [ ]:
arr_members = df['members'].to_numpy()
arr_members

array([200630, 793665, 114262, ...,    219,    175,    142])

In [ ]:
arr_type = df['type'].to_numpy()
arr_type

array([nan, nan, 'TV', ..., nan, 'OVA', nan], dtype=object)

In [ ]:
arr_rating.ravel()[np.random.choice(arr_rating.size, 3442, replace=False)] = np.nan
arr_rating

array([ nan,  nan,  nan, ..., 4.88, 4.98,  nan])

In [ ]:
arr_type.ravel()[np.random.choice(arr_type.size, 3442, replace=False)] = np.nan
arr_type

array([nan, nan, 'TV', ..., nan, 'OVA', nan], dtype=object)

In [ ]:
arr_members = pd.to_numeric(arr_members, errors='coerce')
arr_members =arr_members.astype(float)

In [ ]:
arr_members.ravel()[np.random.choice(arr_members.size, 3442, replace=False)] = np.nan
arr_members

array([2.00630e+05, 7.93665e+05,         nan, ..., 2.19000e+02,
       1.75000e+02,         nan])

In [ ]:
arr_rating = imp_median.fit_transform([arr_rating])
arr_rating

array([[9.17, 9.13, 9.05, ..., 4.15, 4.88, 4.98]])

In [ ]:
np.isnan(arr_rating).any()

False

In [ ]:
arr_type = imp_freq.fit_transform([arr_type])
arr_type

array([['TV', 'TV', 'TV', ..., 'OVA', 'OVA', 'OVA']], dtype=object)

In [ ]:
arr_members = imp_mean.fit_transform([arr_members])
arr_members

array([[2.00630e+05, 7.93665e+05, 1.51266e+05, ..., 1.83000e+02,
        2.19000e+02, 1.75000e+02]])

In [ ]:
np.isnan(arr_rating).any()

False

In [ ]:
 print(pd.unique(df['type']))

[nan 'TV' 'Movie' 'OVA' 'Special' 'ONA' 'Music']


In [ ]:
df_with_dummies = pd.get_dummies(df['type'])
df_with_dummies

Movie  Music  ONA  OVA  Special  TV
0          0      0    0    0        0   0
1          0      0    0    0        0   0
2          0      0    0    0        0   1
3          0      0    0    0        0   1
4          0      0    0    0        0   0
...      ...    ...  ...  ...      ...  ..
12289      0      0    0    1        0   0
12290      0      0    0    0        0   0
12291      0      0    0    0        0   0
12292      0      0    0    1        0   0
12293      0      0    0    0        0   0

[12294 rows x 6 columns]